### PR TITLE
Implement most of GET methods

### PR DESCRIPTION
**Pull request by liangxin1300**
Here is record: https://asciinema.org/a/227421

According to cib.xml, there are two parts about these methods:
1. configuration
2. status

In golang, if we want to translate data from xml to json, we'd better define structs for data, which is too large to write them manually;
So I created [cibToGo](url), which is a tool we want to generate go structs automatic when go building;
For "configuration", cibToGo will read the cib schema as its input, and for "status", I used "crm_mon -X" to created xml file as this tool's input, from my development environment ;
At last, cibToGo will generate api_structs.go file, which is used for translation in golang.

Changes include:
* Pretty print by default
  I think it will be easy to read the json output that we provide pretty print by default.
  And, we could change it as normal print by using
  `-H "PrettyPrint:0"` in our client code, for some efficiency reasons.

* Get methods for these apis:
 /api/v1/configuration/cluster_property
/api/v1/configuration/rsc_defaults
/api/v1/configuration/op_defaults
/api/v1/configuration/resources
/api/v1/configuration/resources/:id
/api/v1/configuration/primitives
/api/v1/configuration/primitives/:id
/api/v1/configuration/groups
/api/v1/configuration/groups/:id
/api/v1/configuration/groups/:id/:primitiveId
/api/v1/configuration/masters
/api/v1/configuration/masters/:id
/api/v1/configuration/clones
/api/v1/configuration/clones/:id
/api/v1/configuration/bundles
/api/v1/configuration/bundles/:id
/api/v1/configuration/bundles/:id/:primitiveId
/api/v1/configuration/nodes
/api/v1/configuration/nodes/:id
/api/v1/configuration/constraints
/api/v1/configuration/constraints/:id
/api/v1/configuration/locations
/api/v1/configuration/locations/:id
/api/v1/configuration/colocations
/api/v1/configuration/colocations/:id
/api/v1/configuration/orders
/api/v1/configuration/orders/:id
/api/v1/status/summary
/api/v1/status/nodes
/api/v1/status/nodes/:id
/api/v1/status/resources
/api/v1/status/resources/:id
/api/v1/status/failures
/api/v1/status/failures/:node

### CODE REVIEW

**Comment by krig** [comment]
Hi Xin, I have finally gotten to reviewing your pull request, sorry for taking so long!

I think to merge this (and considering the earlier API work too), there should be at least some basic test coverage included.

**Comment by krig** [comment]
Hi Xin, please rebase this change on top of `master` so that we get testing and linting via Travis and Code Climate :)

**Review by krig — CHANGES_REQUESTED** [review]
Please rebase on master to get the latest test setup

**Comment by liangxin1300** [comment]
Hi krig, I have created another PR #23 , based on current master code, 
I will close this one

**Pull request closed without merging**
