### PR TITLE
Initial metrics implementation

### PR DESCRIPTION
**Pull request by krig**

### CODE REVIEW

**Comment by ayoub-belarbi** [comment]
Love it!! so far looks good for me, but I think it's still WIP right ?

**Comment by krig** [comment]
> I think it's still WIP right ?

Yeah, at least deciding what the actual metrics should be and tagging them nicely and so on..

**Comment by ayoub-belarbi** [comment]
LGTM :+1: Thanks @krig !

**Review by diegoakechi — APPROVED** [review]
LGTM! Nice Work!

**Pull request merged**
